export class TurnoPaciente {
  fechaSolicitada:string;
  emailPaciente:string;
  estado:string;
  canceladoComentario:string;
  resena:string;
  verResena:string;
  encuesta:string;
  atencion:string;
  fechaFinalizado:string;
  especialidad:string;
  estadoEspecialista:string;
  emailEspecilista:string;
  apellidoPaciente:string;
  nombrePaciente:string;
  apellidoEspecilista:string;
  nombreEspecilista:string;
  fotoEspecilista:string;
  fotoPerfilUnoPaciente:string;
  fotoPerfilDosPaciente:string;
  diagnostico:string;
  altura:string;
  peso:string;
  temperatura:string;
  presion:string;
  clave1:string;
  valor1:string;
  clave2:string;
  valor2:string;
  clave3:string;
  valor3:string;

  constructor(
    fechaSolicitada:string,
    emailPaciente:string,
    estado:string,
    canceladoComentario:string,
    resena:string,
    verResena:string,
    encuesta:string,
    atencion:string,
    fechaFinalizado:string,
    especialidad:string,
    estadoEspecialista:string,
    emailEspecilista:string,
    apellidoPaciente:string,
    nombrePaciente:string,
    apellidoEspecilista:string,
    nombreEspecilista:string,
    fotoEspecilista:string,
    fotoPerfilUnoPaciente:string,
    fotoPerfilDosPaciente:string,
    diagnostico:string,
    altura:string,
    peso:string,
    temperatura:string,
    presion:string,
    clave1:string,
    valor1:string,
    clave2:string,
    valor2:string,
    clave3:string,
    valor3:string,
    ){
      this.fechaSolicitada=fechaSolicitada;
      this.emailPaciente=emailPaciente;
      this.estado=estado;
      this.canceladoComentario=canceladoComentario;
      this.resena=resena;
      this.verResena=verResena;
      this.encuesta=encuesta;
      this.atencion=atencion;
      this.fechaFinalizado=fechaFinalizado;
      this.especialidad=especialidad;
      this.estadoEspecialista=estadoEspecialista;
      this.emailEspecilista=emailEspecilista;
      this.apellidoPaciente=apellidoPaciente;
      this.nombrePaciente=nombrePaciente;
      this.apellidoEspecilista=apellidoEspecilista;
      this.nombreEspecilista=nombreEspecilista;
      this.fotoEspecilista=fotoEspecilista;
      this.fotoPerfilUnoPaciente=fotoPerfilUnoPaciente;
      this.fotoPerfilDosPaciente=fotoPerfilDosPaciente;
      this.diagnostico=diagnostico;
      this.altura=altura;
      this.peso=peso;
      this.temperatura=temperatura;
      this.presion=presion;
      this.clave1=clave1;
      this.valor1=valor1;
      this.clave2=clave2;
      this.valor2=valor2;
      this.clave3=clave3;
      this.valor3=valor3;
    }
}
